language: c

env:
  matrix:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
  global:
    secure: T+2V0r3l7TkXGaJisTgeNsy8xpOSzes/xEGXvPpVPUDZUiF04azxLCeDmjTr8aPialhpZvQeIC7pJPsLNyPT5Hk9zZIcvekkhi7dV/G/fY0VSwdN0RQSJrxwrBoNde0IxTYU0xBrJm0OYba7g2GMfnC2bc2FiF8JrL20LohrAaI=

install:
  - sudo apt-add-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu `lsb_release -cs`/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-get update
  - sudo apt-get install r-base-core
  - wget -q -O - http://yihui.name/xran/r-config | bash

script:
  - cd ..; rm -f *.tar.gz; R CMD build $R_PKG
  - R CMD check $R_PKG*.tar.gz --no-manual
  - cd $R_PKG

after_success:
  - (wget -q -O - http://yihui.name/xran/r-xran | bash)
