language: c

env:
  - R_LIBS_USER=~/R R_PKG="$(basename $TRAVIS_REPO_SLUG)"

install:
  - sudo apt-add-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu `lsb_release -cs`/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-get update
  - sudo apt-get install r-base-dev
  - "[ ! -d ~/R ] && mkdir ~/R"
  - "wget -q -O - http://yihui.name/xran/r-config | bash"

script:
  - cd ..; rm -f *.tar.gz; R CMD build $R_PKG
  - R CMD check *.tar.gz --no-manual
